name: build
on: [push]
jobs:
  build:
    env:
      GOTOOLCHAIN: local
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        id: go
      - name: Build webhook binary
        run: go build -v -o /out
      # - name: Test
      #   run: go test -v ./...
      - run: ls -al
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webhook
          path: ./out/
          if-no-files-found: warn
          overwrite: true
          compression-level: 0