name: build
on: [push]
jobs:
  build:
    env:
      GOTOOLCHAIN: local
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        id: go
      - run: mkdir -p build/${{ matrix.os }}
      - name: Build webhook binary
        run: go build -v -o build/${{ matrix.os }}/
      # - name: Test
      #   run: go test -v ./...
      - run: ls -al build
      - run: ls -al build/${{ matrix.os }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webhook
          path: build/${{ matrix.os }}/webhook
          if-no-files-found: warn
          overwrite: true
          compression-level: 0
      - name: Create the release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          tag: 1.0
          title: Webhook release
