name: build
on: [push]
jobs:
  build:
    env:
      GOTOOLCHAIN: local
    strategy:
      matrix:
        go-version: [1.22.x, 1.23.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        id: go
      - name: Build webhook binary
        run: GOOS=linux GOARCH=amd64 go build -v
      # - name: Test
      #   run: go test -v ./...
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          path: ./webhook
          if-no-files-found: warn
          retention-days: 1
          overwrite: true
